# syntax=docker/dockerfile:1
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/shared/package*.json ./packages/shared/

RUN npm config set registry https://registry.npmmirror.com
RUN npm ci --workspace=@yiai/shared --workspace=@yiai/web

COPY . .

RUN npm run build -w packages/shared && npm run build -w apps/web

FROM nginx:stable-alpine

ARG NGINX_CONFIG=infra/nginx/nginx.conf

COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
COPY ${NGINX_CONFIG} /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
